export interface NYSEStock {
  symbol: string
  name: string
  sector: string
  industry: string
}

export const NYSE_STOCKS: NYSEStock[] = [
  // Technology
  { symbol: "AAPL", name: "Apple Inc.", sector: "Technology", industry: "Consumer Electronics" },
  { symbol: "MSFT", name: "Microsoft Corporation", sector: "Technology", industry: "Software" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A", sector: "Technology", industry: "Internet Content & Information" },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary", industry: "Internet Retail" },
  { symbol: "META", name: "Meta Platforms Inc.", sector: "Technology", industry: "Social Media" },
  { symbol: "NVDA", name: "NVIDIA Corporation", sector: "Technology", industry: "Semiconductors" },
  { symbol: "TSLA", name: "Tesla Inc.", sector: "Consumer Discretionary", industry: "Auto Manufacturers" },
  { symbol: "NFLX", name: "Netflix Inc.", sector: "Communication Services", industry: "Entertainment" },
  { symbol: "ADBE", name: "Adobe Inc.", sector: "Technology", industry: "Software" },
  { symbol: "CRM", name: "Salesforce Inc.", sector: "Technology", industry: "Software" },
  { symbol: "ORCL", name: "Oracle Corporation", sector: "Technology", industry: "Software" },
  { symbol: "INTC", name: "Intel Corporation", sector: "Technology", industry: "Semiconductors" },
  { symbol: "CSCO", name: "Cisco Systems Inc.", sector: "Technology", industry: "Networking Equipment" },
  { symbol: "IBM", name: "International Business Machines Corp.", sector: "Technology", industry: "IT Services" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc.", sector: "Technology", industry: "Semiconductors" },
  { symbol: "QCOM", name: "Qualcomm Inc.", sector: "Technology", industry: "Semiconductors" },
  { symbol: "TXN", name: "Texas Instruments Inc.", sector: "Technology", industry: "Semiconductors" },
  { symbol: "AVGO", name: "Broadcom Inc.", sector: "Technology", industry: "Semiconductors" },
  { symbol: "MU", name: "Micron Technology Inc.", sector: "Technology", industry: "Semiconductors" },
  { symbol: "AMAT", name: "Applied Materials Inc.", sector: "Technology", industry: "Semiconductor Equipment" },

  // Financial Services
  { symbol: "JPM", name: "JPMorgan Chase & Co.", sector: "Financial Services", industry: "Banks" },
  { symbol: "BAC", name: "Bank of America Corp.", sector: "Financial Services", industry: "Banks" },
  { symbol: "WFC", name: "Wells Fargo & Company", sector: "Financial Services", industry: "Banks" },
  { symbol: "GS", name: "Goldman Sachs Group Inc.", sector: "Financial Services", industry: "Investment Banking" },
  { symbol: "MS", name: "Morgan Stanley", sector: "Financial Services", industry: "Investment Banking" },
  { symbol: "C", name: "Citigroup Inc.", sector: "Financial Services", industry: "Banks" },
  { symbol: "AXP", name: "American Express Company", sector: "Financial Services", industry: "Credit Services" },
  { symbol: "V", name: "Visa Inc.", sector: "Financial Services", industry: "Credit Services" },
  { symbol: "MA", name: "Mastercard Inc.", sector: "Financial Services", industry: "Credit Services" },
  { symbol: "PYPL", name: "PayPal Holdings Inc.", sector: "Financial Services", industry: "Credit Services" },
  { symbol: "SQ", name: "Block Inc.", sector: "Financial Services", industry: "Credit Services" },
  { symbol: "COF", name: "Capital One Financial Corp.", sector: "Financial Services", industry: "Banks" },
  { symbol: "USB", name: "U.S. Bancorp", sector: "Financial Services", industry: "Banks" },
  { symbol: "PNC", name: "PNC Financial Services Group Inc.", sector: "Financial Services", industry: "Banks" },
  { symbol: "TFC", name: "Truist Financial Corporation", sector: "Financial Services", industry: "Banks" },
  { symbol: "BK", name: "Bank of New York Mellon Corp.", sector: "Financial Services", industry: "Asset Management" },
  { symbol: "STT", name: "State Street Corp.", sector: "Financial Services", industry: "Asset Management" },
  { symbol: "BLK", name: "BlackRock Inc.", sector: "Financial Services", industry: "Asset Management" },
  { symbol: "SCHW", name: "Charles Schwab Corp.", sector: "Financial Services", industry: "Investment Services" },
  { symbol: "ICE", name: "Intercontinental Exchange Inc.", sector: "Financial Services", industry: "Financial Exchanges" },

  // Healthcare
  { symbol: "JNJ", name: "Johnson & Johnson", sector: "Healthcare", industry: "Pharmaceuticals" },
  { symbol: "PFE", name: "Pfizer Inc.", sector: "Healthcare", industry: "Pharmaceuticals" },
  { symbol: "UNH", name: "UnitedHealth Group Inc.", sector: "Healthcare", industry: "Managed Healthcare" },
  { symbol: "ABBV", name: "AbbVie Inc.", sector: "Healthcare", industry: "Pharmaceuticals" },
  { symbol: "MRK", name: "Merck & Co. Inc.", sector: "Healthcare", industry: "Pharmaceuticals" },
  { symbol: "TMO", name: "Thermo Fisher Scientific Inc.", sector: "Healthcare", industry: "Life Sciences" },
  { symbol: "ABT", name: "Abbott Laboratories", sector: "Healthcare", industry: "Medical Devices" },
  { symbol: "DHR", name: "Danaher Corporation", sector: "Healthcare", industry: "Life Sciences" },
  { symbol: "BMY", name: "Bristol-Myers Squibb Company", sector: "Healthcare", industry: "Pharmaceuticals" },
  { symbol: "LLY", name: "Eli Lilly and Company", sector: "Healthcare", industry: "Pharmaceuticals" },
  { symbol: "AMGN", name: "Amgen Inc.", sector: "Healthcare", industry: "Biotechnology" },
  { symbol: "GILD", name: "Gilead Sciences Inc.", sector: "Healthcare", industry: "Biotechnology" },
  { symbol: "BIIB", name: "Biogen Inc.", sector: "Healthcare", industry: "Biotechnology" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc.", sector: "Healthcare", industry: "Biotechnology" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc.", sector: "Healthcare", industry: "Biotechnology" },
  { symbol: "ISRG", name: "Intuitive Surgical Inc.", sector: "Healthcare", industry: "Medical Devices" },
  { symbol: "SYK", name: "Stryker Corporation", sector: "Healthcare", industry: "Medical Devices" },
  { symbol: "BDX", name: "Becton, Dickinson and Company", sector: "Healthcare", industry: "Medical Devices" },
  { symbol: "EW", name: "Edwards Lifesciences Corp.", sector: "Healthcare", industry: "Medical Devices" },
  { symbol: "ZTS", name: "Zoetis Inc.", sector: "Healthcare", industry: "Animal Health" },

  // Consumer Discretionary
  { symbol: "HD", name: "Home Depot Inc.", sector: "Consumer Discretionary", industry: "Home Improvement Retail" },
  { symbol: "LOW", name: "Lowe's Companies Inc.", sector: "Consumer Discretionary", industry: "Home Improvement Retail" },
  { symbol: "MCD", name: "McDonald's Corporation", sector: "Consumer Discretionary", industry: "Restaurants" },
  { symbol: "SBUX", name: "Starbucks Corporation", sector: "Consumer Discretionary", industry: "Restaurants" },
  { symbol: "NKE", name: "Nike Inc.", sector: "Consumer Discretionary", industry: "Footwear & Accessories" },
  { symbol: "DIS", name: "Walt Disney Company", sector: "Consumer Discretionary", industry: "Entertainment" },
  { symbol: "CMG", name: "Chipotle Mexican Grill Inc.", sector: "Consumer Discretionary", industry: "Restaurants" },
  { symbol: "YUM", name: "Yum! Brands Inc.", sector: "Consumer Discretionary", industry: "Restaurants" },
  { symbol: "TJX", name: "TJX Companies Inc.", sector: "Consumer Discretionary", industry: "Apparel Retail" },
  { symbol: "ROST", name: "Ross Stores Inc.", sector: "Consumer Discretionary", industry: "Apparel Retail" },
  { symbol: "ULTA", name: "Ulta Beauty Inc.", sector: "Consumer Discretionary", industry: "Specialty Retail" },
  { symbol: "LULU", name: "Lululemon Athletica Inc.", sector: "Consumer Discretionary", industry: "Apparel Retail" },
  { symbol: "TGT", name: "Target Corporation", sector: "Consumer Discretionary", industry: "General Merchandise Stores" },
  { symbol: "COST", name: "Costco Wholesale Corporation", sector: "Consumer Discretionary", industry: "General Merchandise Stores" },
  { symbol: "BBY", name: "Best Buy Co. Inc.", sector: "Consumer Discretionary", industry: "Consumer Electronics Retail" },
  { symbol: "GME", name: "GameStop Corp.", sector: "Consumer Discretionary", industry: "Specialty Retail" },
  { symbol: "AMZN", name: "Amazon.com Inc.", sector: "Consumer Discretionary", industry: "Internet Retail" },
  { symbol: "EBAY", name: "eBay Inc.", sector: "Consumer Discretionary", industry: "Internet Retail" },
  { symbol: "ETSY", name: "Etsy Inc.", sector: "Consumer Discretionary", industry: "Internet Retail" },
  { symbol: "W", name: "Wayfair Inc.", sector: "Consumer Discretionary", industry: "Internet Retail" },

  // Consumer Staples
  { symbol: "WMT", name: "Walmart Inc.", sector: "Consumer Staples", industry: "Hypermarkets & Super Centers" },
  { symbol: "PG", name: "Procter & Gamble Co.", sector: "Consumer Staples", industry: "Household Products" },
  { symbol: "KO", name: "Coca-Cola Company", sector: "Consumer Staples", industry: "Beverages" },
  { symbol: "PEP", name: "PepsiCo Inc.", sector: "Consumer Staples", industry: "Beverages" },
  { symbol: "CL", name: "Colgate-Palmolive Company", sector: "Consumer Staples", industry: "Household Products" },
  { symbol: "KMB", name: "Kimberly-Clark Corporation", sector: "Consumer Staples", industry: "Household Products" },
  { symbol: "GIS", name: "General Mills Inc.", sector: "Consumer Staples", industry: "Packaged Foods" },
  { symbol: "K", name: "Kellogg Company", sector: "Consumer Staples", industry: "Packaged Foods" },
  { symbol: "HSY", name: "Hershey Company", sector: "Consumer Staples", industry: "Confectionery" },
  { symbol: "MDLZ", name: "Mondelez International Inc.", sector: "Consumer Staples", industry: "Confectionery" },
  { symbol: "KHC", name: "Kraft Heinz Company", sector: "Consumer Staples", industry: "Packaged Foods" },
  { symbol: "CLX", name: "Clorox Company", sector: "Consumer Staples", industry: "Household Products" },
  { symbol: "CHD", name: "Church & Dwight Co. Inc.", sector: "Consumer Staples", industry: "Household Products" },
  { symbol: "SJM", name: "J.M. Smucker Company", sector: "Consumer Staples", industry: "Packaged Foods" },
  { symbol: "CPB", name: "Campbell Soup Company", sector: "Consumer Staples", industry: "Packaged Foods" },
  { symbol: "CAG", name: "Conagra Brands Inc.", sector: "Consumer Staples", industry: "Packaged Foods" },
  { symbol: "TSN", name: "Tyson Foods Inc.", sector: "Consumer Staples", industry: "Meat Products" },
  { symbol: "HRL", name: "Hormel Foods Corporation", sector: "Consumer Staples", industry: "Meat Products" },
  { symbol: "SYY", name: "Sysco Corporation", sector: "Consumer Staples", industry: "Food Distribution" },
  { symbol: "KR", name: "Kroger Co.", sector: "Consumer Staples", industry: "Grocery Stores" },

  // Energy
  { symbol: "XOM", name: "Exxon Mobil Corporation", sector: "Energy", industry: "Oil & Gas Integrated" },
  { symbol: "CVX", name: "Chevron Corporation", sector: "Energy", industry: "Oil & Gas Integrated" },
  { symbol: "COP", name: "ConocoPhillips", sector: "Energy", industry: "Oil & Gas E&P" },
  { symbol: "EOG", name: "EOG Resources Inc.", sector: "Energy", industry: "Oil & Gas E&P" },
  { symbol: "SLB", name: "Schlumberger Limited", sector: "Energy", industry: "Oil & Gas Equipment & Services" },
  { symbol: "HAL", name: "Halliburton Company", sector: "Energy", industry: "Oil & Gas Equipment & Services" },
  { symbol: "BKR", name: "Baker Hughes Company", sector: "Energy", industry: "Oil & Gas Equipment & Services" },
  { symbol: "MPC", name: "Marathon Petroleum Corporation", sector: "Energy", industry: "Oil & Gas Refining & Marketing" },
  { symbol: "PSX", name: "Phillips 66", sector: "Energy", industry: "Oil & Gas Refining & Marketing" },
  { symbol: "VLO", name: "Valero Energy Corporation", sector: "Energy", industry: "Oil & Gas Refining & Marketing" },
  { symbol: "KMI", name: "Kinder Morgan Inc.", sector: "Energy", industry: "Oil & Gas Midstream" },
  { symbol: "WMB", name: "Williams Companies Inc.", sector: "Energy", industry: "Oil & Gas Midstream" },
  { symbol: "OKE", name: "ONEOK Inc.", sector: "Energy", industry: "Oil & Gas Midstream" },
  { symbol: "ET", name: "Energy Transfer LP", sector: "Energy", industry: "Oil & Gas Midstream" },
  { symbol: "EPD", name: "Enterprise Products Partners LP", sector: "Energy", industry: "Oil & Gas Midstream" },
  { symbol: "PXD", name: "Pioneer Natural Resources Company", sector: "Energy", industry: "Oil & Gas E&P" },
  { symbol: "OXY", name: "Occidental Petroleum Corporation", sector: "Energy", industry: "Oil & Gas E&P" },
  { symbol: "DVN", name: "Devon Energy Corporation", sector: "Energy", industry: "Oil & Gas E&P" },
  { symbol: "FANG", name: "Diamondback Energy Inc.", sector: "Energy", industry: "Oil & Gas E&P" },
  { symbol: "MRO", name: "Marathon Oil Corporation", sector: "Energy", industry: "Oil & Gas E&P" },

  // Industrial
  { symbol: "BA", name: "Boeing Company", sector: "Industrial", industry: "Aerospace & Defense" },
  { symbol: "CAT", name: "Caterpillar Inc.", sector: "Industrial", industry: "Construction & Mining Equipment" },
  { symbol: "GE", name: "General Electric Company", sector: "Industrial", industry: "Industrial Conglomerates" },
  { symbol: "HON", name: "Honeywell International Inc.", sector: "Industrial", industry: "Industrial Conglomerates" },
  { symbol: "MMM", name: "3M Company", sector: "Industrial", industry: "Industrial Conglomerates" },
  { symbol: "UPS", name: "United Parcel Service Inc.", sector: "Industrial", industry: "Air Freight & Logistics" },
  { symbol: "FDX", name: "FedEx Corporation", sector: "Industrial", industry: "Air Freight & Logistics" },
  { symbol: "LMT", name: "Lockheed Martin Corporation", sector: "Industrial", industry: "Aerospace & Defense" },
  { symbol: "RTX", name: "Raytheon Technologies Corporation", sector: "Industrial", industry: "Aerospace & Defense" },
  { symbol: "NOC", name: "Northrop Grumman Corporation", sector: "Industrial", industry: "Aerospace & Defense" },
  { symbol: "GD", name: "General Dynamics Corporation", sector: "Industrial", industry: "Aerospace & Defense" },
  { symbol: "EMR", name: "Emerson Electric Co.", sector: "Industrial", industry: "Electrical Equipment" },
  { symbol: "ETN", name: "Eaton Corporation plc", sector: "Industrial", industry: "Electrical Equipment" },
  { symbol: "PH", name: "Parker-Hannifin Corporation", sector: "Industrial", industry: "Industrial Machinery" },
  { symbol: "DOV", name: "Dover Corporation", sector: "Industrial", industry: "Industrial Machinery" },
  { symbol: "ITW", name: "Illinois Tool Works Inc.", sector: "Industrial", industry: "Industrial Machinery" },
  { symbol: "CMI", name: "Cummins Inc.", sector: "Industrial", industry: "Industrial Machinery" },
  { symbol: "DE", name: "Deere & Company", sector: "Industrial", industry: "Agricultural Equipment" },
  { symbol: "CNHI", name: "CNH Industrial N.V.", sector: "Industrial", industry: "Agricultural Equipment" },
  { symbol: "AGCO", name: "AGCO Corporation", sector: "Industrial", industry: "Agricultural Equipment" },

  // Utilities
  { symbol: "NEE", name: "NextEra Energy Inc.", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "DUK", name: "Duke Energy Corporation", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "SO", name: "Southern Company", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "D", name: "Dominion Energy Inc.", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "AEP", name: "American Electric Power Company Inc.", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "EXC", name: "Exelon Corporation", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "XEL", name: "Xcel Energy Inc.", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "PEG", name: "Public Service Enterprise Group Inc.", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "ED", name: "Consolidated Edison Inc.", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "ES", name: "Eversource Energy", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "WEC", name: "WEC Energy Group Inc.", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "FE", name: "FirstEnergy Corp.", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "ETR", name: "Entergy Corporation", sector: "Utilities", industry: "Electric Utilities" },
  { symbol: "AWK", name: "American Water Works Company Inc.", sector: "Utilities", industry: "Water Utilities" },
  { symbol: "SRE", name: "Sempra Energy", sector: "Utilities", industry: "Gas Utilities" },
  { symbol: "OKE", name: "ONEOK Inc.", sector: "Utilities", industry: "Gas Utilities" },
  { symbol: "WMB", name: "Williams Companies Inc.", sector: "Utilities", industry: "Gas Utilities" },
  { symbol: "KMI", name: "Kinder Morgan Inc.", sector: "Utilities", industry: "Gas Utilities" },
  { symbol: "ET", name: "Energy Transfer LP", sector: "Utilities", industry: "Gas Utilities" },
  { symbol: "EPD", name: "Enterprise Products Partners LP", sector: "Utilities", industry: "Gas Utilities" },

  // Real Estate
  { symbol: "AMT", name: "American Tower Corporation", sector: "Real Estate", industry: "REITs" },
  { symbol: "PLD", name: "Prologis Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "CCI", name: "Crown Castle Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "EQIX", name: "Equinix Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "PSA", name: "Public Storage", sector: "Real Estate", industry: "REITs" },
  { symbol: "EXR", name: "Extra Space Storage Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "DLR", name: "Digital Realty Trust Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "WELL", name: "Welltower Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "VTR", name: "Ventas Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "PEAK", name: "Healthpeak Properties Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "SPG", name: "Simon Property Group Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "O", name: "Realty Income Corporation", sector: "Real Estate", industry: "REITs" },
  { symbol: "STOR", name: "STORE Capital Corporation", sector: "Real Estate", industry: "REITs" },
  { symbol: "WPC", name: "W.P. Carey Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "NNN", name: "National Retail Properties Inc.", sector: "Real Estate", industry: "REITs" },
  { symbol: "FRT", name: "Federal Realty Investment Trust", sector: "Real Estate", industry: "REITs" },
  { symbol: "REG", name: "Regency Centers Corporation", sector: "Real Estate", industry: "REITs" },
  { symbol: "KIM", name: "Kimco Realty Corporation", sector: "Real Estate", industry: "REITs" },
  { symbol: "MAC", name: "Macerich Company", sector: "Real Estate", industry: "REITs" },
  { symbol: "BXP", name: "Boston Properties Inc.", sector: "Real Estate", industry: "REITs" },

  // Communication Services
  { symbol: "VZ", name: "Verizon Communications Inc.", sector: "Communication Services", industry: "Telecom Services" },
  { symbol: "T", name: "AT&T Inc.", sector: "Communication Services", industry: "Telecom Services" },
  { symbol: "CMCSA", name: "Comcast Corporation", sector: "Communication Services", industry: "Cable & Satellite" },
  { symbol: "CHTR", name: "Charter Communications Inc.", sector: "Communication Services", industry: "Cable & Satellite" },
  { symbol: "DISCA", name: "Discovery Inc. Class A", sector: "Communication Services", industry: "Broadcasting" },
  { symbol: "DISCK", name: "Discovery Inc. Class C", sector: "Communication Services", industry: "Broadcasting" },
  { symbol: "VIAC", name: "ViacomCBS Inc.", sector: "Communication Services", industry: "Broadcasting" },
  { symbol: "FOX", name: "Fox Corporation Class A", sector: "Communication Services", industry: "Broadcasting" },
  { symbol: "FOXA", name: "Fox Corporation Class B", sector: "Communication Services", industry: "Broadcasting" },
  { symbol: "TWTR", name: "Twitter Inc.", sector: "Communication Services", industry: "Social Media" },
  { symbol: "SNAP", name: "Snap Inc.", sector: "Communication Services", industry: "Social Media" },
  { symbol: "PINS", name: "Pinterest Inc.", sector: "Communication Services", industry: "Social Media" },
  { symbol: "MTCH", name: "Match Group Inc.", sector: "Communication Services", industry: "Internet Content & Information" },
  { symbol: "IAC", name: "IAC/InterActiveCorp", sector: "Communication Services", industry: "Internet Content & Information" },
  { symbol: "TRIP", name: "TripAdvisor Inc.", sector: "Communication Services", industry: "Internet Content & Information" },
  { symbol: "EXPE", name: "Expedia Group Inc.", sector: "Communication Services", industry: "Internet Content & Information" },
  { symbol: "BKNG", name: "Booking Holdings Inc.", sector: "Communication Services", industry: "Internet Content & Information" },
  { symbol: "TRVG", name: "Trivago N.V.", sector: "Communication Services", industry: "Internet Content & Information" },
  { symbol: "LYFT", name: "Lyft Inc.", sector: "Communication Services", industry: "Internet Content & Information" },
  { symbol: "UBER", name: "Uber Technologies Inc.", sector: "Communication Services", industry: "Internet Content & Information" },

  // Materials
  { symbol: "LIN", name: "Linde plc", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "APD", name: "Air Products and Chemicals Inc.", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "SHW", name: "Sherwin-Williams Company", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "PPG", name: "PPG Industries Inc.", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "EMN", name: "Eastman Chemical Company", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "IFF", name: "International Flavors & Fragrances Inc.", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "DD", name: "DuPont de Nemours Inc.", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "DOW", name: "Dow Inc.", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "LYB", name: "LyondellBasell Industries N.V.", sector: "Materials", industry: "Specialty Chemicals" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc.", sector: "Materials", industry: "Copper" },
  { symbol: "SCCO", name: "Southern Copper Corporation", sector: "Materials", industry: "Copper" },
  { symbol: "TECK", name: "Teck Resources Limited", sector: "Materials", industry: "Coal" },
  { symbol: "NEM", name: "Newmont Corporation", sector: "Materials", industry: "Gold" },
  { symbol: "GOLD", name: "Barrick Gold Corporation", sector: "Materials", industry: "Gold" },
  { symbol: "AA", name: "Alcoa Corporation", sector: "Materials", industry: "Aluminum" },
  { symbol: "X", name: "United States Steel Corporation", sector: "Materials", industry: "Steel" },
  { symbol: "NUE", name: "Nucor Corporation", sector: "Materials", industry: "Steel" },
  { symbol: "STLD", name: "Steel Dynamics Inc.", sector: "Materials", industry: "Steel" },
  { symbol: "RS", name: "Reliance Steel & Aluminum Co.", sector: "Materials", industry: "Steel" },
  { symbol: "PKG", name: "Packaging Corporation of America", sector: "Materials", industry: "Paper & Plastic Products" }
]

export function searchStocks(query: string): NYSEStock[] {
  if (!query) return NYSE_STOCKS.slice(0, 50) // Show top 50 by default
  
  const lowercaseQuery = query.toLowerCase()
  return NYSE_STOCKS.filter(stock => 
    stock.symbol.toLowerCase().includes(lowercaseQuery) ||
    stock.name.toLowerCase().includes(lowercaseQuery) ||
    stock.sector.toLowerCase().includes(lowercaseQuery) ||
    stock.industry.toLowerCase().includes(lowercaseQuery)
  ).slice(0, 100) // Limit to 100 results
}
